### ISSUE TITLE
Calling a shared function while handling UserDataReceived throws exception

### ISSUE THREAD

**Issue by cvause18** [Rufus31415/Sharer#1]
Calling a shared function inside of the event handler (in C#) of the UserDataReceived event throws a System.Exception that reads "Error while calling function [function_name]".

**Comment by Rufus31415** [comment]
Indeed, the architecture of Sharer does not allow it. I'm torn between changing the implementation or simply pointing out that this is a known limitation. Is it blocking for you?

**Comment by cvause18** [comment]
I was able to find a workaround in my case, so it is not blocking. Fantastic library by the way. Thank you for writing it!

**Comment by Rufus31415** [comment]
Thanks :) Don't hesitate to share your work !
