### ISSUE TITLE
Using Library from another Arduino library

### ISSUE THREAD

**Issue by jzarifis** [Rufus31415/Sharer#2]
I am trying to use Sharer from a cpp Arduino library. Valiables(Sharer_ShareVariable) works very nice (read and write) but i am having problem with functions.

Have tried:

Sharer_ShareVoid(MYLIBRARYCLASS::dataUpdated);
 
void MYLIBRARYCLASS::dataUpdated() {

} 
Compiler Error:
......\Arduino\libraries\Sharer\src/Sharer.h:248:76: error: qualified-id in declaration before '[' token
     static const SharerClass::_SharerFunctionArgument functionName ## _args[] = {\

Sharer_ShareVoid(dataUpdated);
 
void MYLIBRARYCLASS::dataUpdated() {

} 

OR

void dataUpdated() {

} 

Compiler Error:
......\Arduino\libraries\Sharer\src/Sharer.h:262:561: error: 'this' was not captured for this lambda function
         functionName (_SHARER_GET_OVERRIDE(__VA_ARGS__, _SHARER_DECLARE_CALL10, _SHARER_DECLARE_CALL9_, _SHARER_DECLARE_CALL9,  _SHARER_DECLARE_CALL8_, _SHARER_DECLARE_CALL8,  _SHARER_DECLARE_CALL7_, _SHARER_DECLARE_CALL7,  _SHARER_DECLARE_CALL6_, _SHARER_DECLARE_CALL6,  _SHARER_DECLARE_CALL5_, _SHARER_DECLARE_CALL5,  _SHARER_DECLARE_CALL4_, _SHARER_DECLARE_CALL4,  _SHARER_DECLARE_CALL3_, _SHARER_DECLARE_CALL3,  _SHARER_DECLARE_CALL2_, _SHARER_DECLARE_CALL2, _SHARER_DECLARE_CALL1_, _SHARER_DECLARE_CALL1, _SHARER_DECLARE_CALL0)(functionName, __VA_ARGS__) );\
 
 
 As i wrote before class member properties work very well with Sharer_ShareVariable, please advise

**Comment by Rufus31415** [comment]
Can you share the whole file here please ?

**Comment by jzarifis** [comment]
[Sharer_Prototype.zip](https://github.com/Rufus31415/Sharer/files/7675319/Sharer_Prototype.zip)

I have prepared(attached) a light sketch with lib to reproduce

**Comment by Rufus31415** [comment]
This is indeed due to the fact that you share a class method. Sharer is global, it will not know on which instance of your Sample class it will have to call the function (hence the error "'this' was not captured for this lambda function").
As for variable sharing, it's amazing that it compiles. I'm not sure if it works if you instantiate your class several times.
