### ISSUE TITLE
Cannot communicate with Arduino Micro/Leonardo

### ISSUE THREAD

**Issue by VassilyDev** [Rufus31415/Sharer#3]
Hi, I seem to have some sort of problem with your library.
My sketch works fine while using an Arduino Uno, but on Micro and Leonardo there are some issues. 
'The serial communication is connected but Sharer is not available. Ensure that Sharer.Run() is called in loop() function and that setup() function takes less than 10000ms.' is thrown.
For what I read online, DTR and RTS should be enabled on the C# side, but I can't do that since your dll does not accept that parameters (I think).

**Comment by Rufus31415** [comment]
Hi,

Thanks for this relevant remark, I don't have a Micro or Leonardo to test.
Can you try this for me please :

```cs
var connection = new SharerConnection("COM3", 115200);

// Access internal SerialPort object by reflexion
var port = (System.IO.Ports.SerialPort)connection.GetType().GetField("_serialPort", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(connection);

// Find the right RTS / DTR configuration
port.RtsEnable = true;
port.DtrEnable = true;

// Connect now, if it doesn't work, try connect before setting Rts or Dtr
connection.Connect();
```

Can you find a RTS / DTR configuration that works for this type of board?
If this solves your problem, I could publicly expose the properties in SharerConnection

**Comment by VassilyDev** [comment]
That does indeed work, with both RTS and DTR enables.
Thanks!
