### ISSUE TITLE
What I make false?

### ISSUE THREAD

**Issue by zoltantajti** [Rufus31415/Sharer#4]
I try share the printString function:
`
void setup()
{
Sharer.init(115200);
Sharer_ShareFunction(bool, printString, char[], msg);  
}
bool printString(char[] msg)
{
  lcd.clear();
  lcd.print(msg);
  return true;
}`

in C#
`
conn.Call("printString", "HELLO");
`

I want print my message to LCD display.

Error message: Input is a not correct format

**Comment by Rufus31415** [comment]
Unfortunately, it's not possible to share string for now

**Comment by zoltantajti** [comment]
And possible with char[]?

**Comment by Rufus31415** [comment]
It would be possible, but I've never taken the time to do it. The only solution today is to call a function for each character that stores it in an array and a function to say that sending the string is finished.

**Comment by zoltantajti** [comment]
It's impossible, because my char array readed from Digital Combat Simulator restAPI, and contains standard flight datas, etc: AirSpeed, Heading, Altitude. 

I now try write a function with boolean parameters and print my LCD, but, when I attach Sharer, the LCD doesn't write details correctly.
